#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004
#服务别名，注册到zookeerper注册中心的名称
spring:
  application:
    name: zookeeper-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.182.100:2181