server:
  port: 9003

spring:
  application:
    name: sentinel-payment-provider
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: ryualvin100:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'




