server:
  port: 3344

spring:
  application:
    name:  cloud-config-server-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ryualvin/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - springcloud-config
          password: xxxxxx
          username: RyuAlvin
      ####读取分支
      label: master
  #在spring节点下添加rabbitmq相关配置，15672是Web管理界面的端口；5672是MQ访问的端口
  rabbitmq:
    host: ryualvin100
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: configserver3344
    prefer-ip-address: true
    hostname: configserver3344.com

##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'