spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/vhr?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/vhr?serverTimezone=Asia/Tokyo&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false

logging:
  level:
    root: info

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mappers/*.xml
