spring:
  freemarker:
    cache: false
    expose-request-attributes: true #默认false
    expose-session-attributes: true #默认false
    expose-spring-macro-helpers: true #默认true
    suffix: .ftl #spring-boot2.2.0改为了ftlh
    settings:
      { datetimeFormat: yyyy-MM-dd HH:mm:ss }
    request-context-attribute: rc
  # 编码配置
  http:
    encoding:
      charset: utf-8
      force: true
server:
  servlet:
    context-path: /httpclient-demo
  port: 8899